my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "lower_arm"
    robot_base_link: "torso"
    target_frame_topic: "target_frame"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_1

    pd_gains:
        trans_x: {p: 10.0}
        trans_y: {p: 10.0}
        trans_z: {p: 10.0}
        rot_x: {p: 1.0}
        rot_y: {p: 1.0}
        rot_z: {p: 1.0}

my_cartesian_force_controller:
    type: "position_controllers/CartesianForceController"
    end_effector_link: "lower_arm"
    robot_base_link: "torso"
    ft_sensor_ref_link: "sensor_link"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_1
    # - 'wrist_right_axis1'
    # - 'wrist_right_axis2'

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 0.01}
        rot_y: {p: 0.01}
        rot_z: {p: 0.01}

my_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "lower_arm"    # All links below must come before this link
    robot_base_link: "torso"
    ft_sensor_ref_link: "sensor_link"
    compliance_ref_link: "lower_arm"
    target_frame_topic: "target_frame"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_1
    # - 'wrist_right_axis1'
    # - 'wrist_right_axis2'

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 100
        rot_y: 100
        rot_z: 100

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 0.01}
        rot_y: {p: 0.01}
        rot_z: {p: 0.01}        

my_motion_control_handle:
    type: "cartesian_controllers/MotionControlHandle"
    end_effector_link: "lower_arm"
    robot_base_link: "torso"
    target_frame_topic: "target_frame"
    joints:
        - shoulder_right_axis0
        - shoulder_right_axis1
        - shoulder_right_axis2
        - elbow_joint_0
        - elbow_joint_1
        # - 'wrist_right_axis1'
        # - 'wrist_right_axis2'

my_joint_to_cartesian_controller:
    type: "cartesian_controllers/JointControllerAdapter"
    end_effector_link: "lower_arm"
    robot_base_link: "torso"
    target_frame_topic: "/my_cartesian_motion_controller/target_frame"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_1
    # - 'wrist_right_axis1'
    # - 'wrist_right_axis2'

    joint_limits:
      shoulder_right_axis0:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      shoulder_right_axis1:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      shoulder_right_axis2:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      elbow_joint_0:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      elbow_joint_1:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0


my_joint_to_cartesian_controller/joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_1

joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_joint_0
    - elbow_joint_0

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
