generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.03

# Settings for ros_control hardware interface
hardware_interface:
  sim_control_mode: 0
  joints:
    - shoulder_right_axis0
    - shoulder_right_axis1
    - shoulder_right_axis2
    - elbow_right_axis0
    - elbow_right_axis1
    - wrist_right_axis0
    - wrist_right_axis1
    - wrist_right_axis2
    - shoulder_left_axis0
    - shoulder_left_axis1
    - shoulder_left_axis2
    - elbow_left_axis0
    - elbow_left_axis1
    - wrist_left_axis0
    - wrist_left_axis1
    - wrist_left_axis2
    - head_axis0
    - head_axis1
    - head_axis2
